- entity-service-client/build.gradle.kts
- entity-service-client/src/main/java/org/hypertrace/entity/data/service/client/EdsCacheClient.java
- entity-service-client/src/main/java/org/hypertrace/entity/data/service/client/EdsCacheKey.java
- entity-service-client/src/main/java/org/hypertrace/entity/data/service/client/EdsTypeAndIdAttributesCacheKey.java
- entity-service-client/src/main/java/org/hypertrace/entity/data/service/client/exception/NotFoundException.java
- entity-service-client/src/main/java/org/hypertrace/entity/service/client/config/EntityServiceClientCacheConfig.java
- entity-service-client/src/main/java/org/hypertrace/entity/service/client/config/EntityServiceClientConfig.java
- entity-service-client/src/test/java/org/hypertrace/entity/data/service/client/EdsCacheClientTest.java
- entity-service-client/src/test/java/org/hypertrace/entity/data/service/client/EdsTypeAndIdAttributesCacheKeyTest.java
- entity-service-client/src/test/java/org/hypertrace/entity/service/client/config/EntityServiceClientCacheConfigTest.java
- enables the client-side caches for most common types of ID-based queries
- adds new cache for queries based on identifying attributes and type
- exposes the cache-related constants to config
> Expose the config for client side caches, and enable them

- entity-service-impl/src/main/java/org/hypertrace/entity/service/util/DocStoreConverter.java
- entity-service-impl/src/test/java/org/hypertrace/entity/service/util/DocStoreConverterTest.java
`labels EQUALS "foo"` translates to labels contains "foo" and AND chain means that the labels should contain all of the labels on the RHS side.
`labels IN ["foo","bar"]` translates to labels contains at least one of the labels in the RHS side of the filter.
> fix: filtering based on entity labels

- entity-service-impl/build.gradle.kts
- entity-service-impl/src/main/java/org/hypertrace/entity/data/service/DocumentParser.java
- entity-service-impl/src/main/java/org/hypertrace/entity/data/service/EntityDataServiceImpl.java
- entity-service-impl/src/main/java/org/hypertrace/entity/data/service/EntityIdGenerator.java
- entity-service-impl/src/main/java/org/hypertrace/entity/data/service/EntityNormalizer.java
- entity-service-impl/src/main/java/org/hypertrace/entity/data/service/IdentifyingAttributeCache.java
- entity-service-impl/src/test/java/org/hypertrace/entity/data/service/DocumentParserTest.java
- entity-service-impl/src/test/java/org/hypertrace/entity/data/service/EntityNormalizerTest.java
- entity-service-impl/src/test/java/org/hypertrace/entity/data/service/IdentifyingAttributeCacheTest.java
- entity-service/build.gradle.kts
- entity-service/src/integrationTest/java/org/hypertrace/entity/service/service/EntityDataServiceTest.java
- entity-service/src/main/java/org/hypertrace/entity/service/EntityService.java
- entity-type-service-rx-client/build.gradle.kts
The purpose of this change is to allow the upsert API to support entities formed by v1 entity types in addition to the existing v1 support. Both produce the same entity objects, but the data in those entities looks a bit different. V2 typed entities will always have an id, and don't use identifying attributes. V1 typed entities are the reverse, requiring identifying attributes and using those in place of an ID. The move to v2 entity types is to support generating ids dynamically and allowing code to generate and work with many entity attributes, including ID without calling into entity service.
> refactor: add support for upsert of v1 or v2 typed entities

- entity-service-impl/build.gradle.kts
- entity-service/build.gradle.kts
Upgrading the docstore version to latest, which changes the mongo java driver used from 3.12 to 4.1.1. This is because the previous java driver is very old, marked legacy driver by MongoDB and there are a lot of bug fixes in the newer versions.
Most importantly, we are running into some issues with bulk upsert in production and we're trying to see if we see those same issues with the latest Mongo java driver too.
Ran Hypertrace locally with the locally built image and things are working fine.
No functionality is changed, hence no docs needed.
> feat: Upgrading docstore version, which brings 4.1.1 mongo java driver.

- entity-service-impl/build.gradle.kts
- entity-service-impl/src/main/java/org/hypertrace/entity/data/service/EntityDataServiceImpl.java
- entity-service/build.gradle.kts
See https://github.com/hypertrace/document-store/pull/13
The current MongoDB servers we use have a known issue - https://jira.mongodb.org/browse/SERVER-47212
where the findAndModify operation might fail with duplicate key exception and server was supposed to
retry that but it doesn't. Since the fix isn't available in the released MongoDB versions,
we are retrying the upserts in these cases in client layer so that we avoid frequent failures in this layer.
> feat: Upgrading docstore version to workaround a bug fix for a known MongoDB server bug.

- entity-service-client/build.gradle.kts
- entity-service-client/src/main/java/org/hypertrace/entity/service/client/config/EntityServiceClientConfig.java
- entity-service-client/src/test/java/org/hypertrace/entity/data/service/client/EntityDataServiceClientRetriesTest.java
- entity-service-client/src/test/resources/log4j2.properties
Currently, there are no examples on how the GRPC clients or entity service clients can retry the requests, if it makes sense.
Adding unit tests which demonstrate how to do GRPC method retries so that it can be used by client applications.
No changes to the service or client. Just added a few more unit tests.
No changes so no need of new docs.
> Adding unit tests for GRPC client retry code.

- helm/templates/entity-service-config.yaml
- helm/values.yaml
Adds helm configs for enabling support for postgres (see more details at hypertrace/hypertrace#124)
Generate the helm templates locally running the below the commands
- helm dependency update ./helm/
- helm template ./helm/
Cases try by changing below values:
- dataStoreType: "postgres"
- dataStoreType: "mongo"
This specific change may not require, but when we update in docker-compose for postgres, we will document it.
> adding helm configs for supporting postgres

- entity-service-api/src/main/proto/org/hypertrace/entity/data/service/v1/entity_data_request.proto
- entity-service-api/src/main/proto/org/hypertrace/entity/query/service/v1/entity_query_request.proto
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/EntityQueryConverter.java
- entity-service-impl/src/main/java/org/hypertrace/entity/service/util/DocStoreConverter.java
- entity-service-impl/src/test/java/org/hypertrace/entity/query/service/EntityQueryConverterTest.java
- entity-service-impl/src/test/java/org/hypertrace/entity/service/util/DocStoreConverterTest.java
- entity-service/src/integrationTest/java/org/hypertrace/entity/service/service/EntityDataServiceTest.java
https://github.com/hypertrace/entity-service/issues/57
Need this implemented to allow batch fetching for large entities volume
EntityQueryService has limit and offset specified in the proto as part
of the Query message. However, there's no implementation and it's has been
faux attributes.
This adds the implementation of order, limit and offset
> Adds limit and offset implementation

- entity-service-api/src/main/proto/org/hypertrace/entity/data/service/v1/entity_data_request.proto
- entity-service-api/src/main/proto/org/hypertrace/entity/query/service/v1/request.proto
- entity-service-impl/src/main/java/org/hypertrace/entity/service/util/DocStoreConverter.java
- entity-service/src/integrationTest/java/org/hypertrace/entity/service/service/EntityDataServiceTest.java
Addressed the issue: https://github.com/hypertrace/entity-service/issues/58
Add supports for checking if the corresponding field exists in the entity.
- exists: returns matching entities documents that contain a request field
- not_exists: returns list of matching entities documents that don't contain requested field
Note:
The underlying document store already supports the exists/non-exists filter:
- https://github.com/hypertrace/document-store/blob/main/document-store/src/main/java/org/hypertrace/core/documentstore/Filter.java
- Mongo implementation provides its impl - https://github.com/hypertrace/document-store/blob/main/document-store/src/main/java/org/hypertrace/core/documentstore/mongo/MongoCollection.java
- For Postgres, there are few operators not implemented. will create an issue …
> adds supports for exists/not-exists filters

- entity-data-service-rx-client/src/main/java/org/hypertrace/entity/data/service/rxclient/EntityDataClient.java
- entity-service-api/src/main/proto/org/hypertrace/entity/data/service/v1/entity_data_service.proto
- entity-service-client/src/main/java/org/hypertrace/entity/data/service/client/EdsCacheClient.java
- entity-service-client/src/main/java/org/hypertrace/entity/data/service/client/EdsClient.java
- entity-service-client/src/main/java/org/hypertrace/entity/data/service/client/EntityDataServiceClient.java
- entity-service-impl/build.gradle.kts
- entity-service-impl/src/main/java/org/hypertrace/entity/data/service/EntityDataServiceImpl.java
- entity-service/build.gradle.kts
- entity-service/src/integrationTest/java/org/hypertrace/entity/service/service/EntityDataServiceTest.java
See #60 for more details.
Integration tests are verifying the full logic.
This PR depends on https://github.com/hypertrace/document-store/pull/18 so build will fail until that's merged.
> #60 Adding a new API which returns the previous entities before bulk upsert

- entity-service/src/main/java/org/hypertrace/entity/service/EntityServiceConfig.java
As part of the issue - https://github.com/hypertrace/hypertrace/issues/137, where we identified that some sensitive information is logged (password for postgres), we are going with option (a) listed in the issue. There is no need to print `config` here.
> discarding printing of full config to avoid any sensitive data leak

- entity-service-impl/src/main/java/org/hypertrace/entity/data/service/DocumentParser.java
- entity-service-impl/src/main/java/org/hypertrace/entity/data/service/EntityDataServiceImpl.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/EntityQueryServiceImpl.java
- entity-service-impl/src/test/java/org/hypertrace/entity/query/service/EntityQueryConverterTest.java
- entity-service-impl/src/test/java/org/hypertrace/entity/query/service/EntityQueryServiceImplTest.java
- entity-service/src/integrationTest/java/org/hypertrace/entity/service/service/EntityQueryServiceTest.java
- entity-service/src/integrationTest/resources/configs/entity-service/application.conf
https://github.com/hypertrace/entity-service/issues/56
The change is to correctly stream the data from the query apis, so that client doesn't face a data overload. 
Added integration test
> Fix streaming large amount of data from entity-service

- .github/workflows/pr-build.yml
uses `run` instead of `uses` for proto validation job in GHA.
> fix: proto command run instead of uses

- .snyk
- entity-service-impl/build.gradle.kts
- entity-service/build.gradle.kts
- Updates doc-store version to include SQLi fix - hypertrace/document-store#30
- extends expiry for ionetty vulnerability
> chore: bump doc-store version to include SQLi fix

- entity-service/build.gradle.kts
Updates version of libs for netty to address,
- https://github.com/hypertrace/entity-service/runs/1868685880?check_suite_focus=true
- https://snyk.io/vuln/SNYK-JAVA-IONETTY-1020439
- https://snyk.io/vuln/SNYK-JAVA-IONETTY-1070799
> chore: bump version of netty codec and proxy libs to fix the vulnerability 

- entity-service-impl/build.gradle.kts
- entity-service-impl/src/main/java/org/hypertrace/entity/service/util/DocStoreConverter.java
- entity-service-impl/src/test/java/org/hypertrace/entity/service/util/DocStoreConverterTest.java
- entity-service/build.gradle.kts
- entity-service/src/integrationTest/java/org/hypertrace/entity/service/service/EntityDataServiceTest.java
This PR addresses a gap for the handling of searching entities for not matching labels for array type field `attributes.labels` 
Currently, we have support for searching entities for matching labels, but we need similar capabilities to search entities for not matching labels. 
Currently, filtering entities for matching labels `attributes.labels IN (<val1> , <val2>)` is translated to `attributes.labels = <val1> OR attributes.labels = <val2> 
This PR adds support for `attributes.labels NOT_IN (<val1> , <val2>)` by translating it into `attributes.labels != <val1> AND attributes.labels != <val2>` 
- added unit tests
- verified locally running MongoDB with the following data and query
Data:
```
db.mytest.insertOne(
{ item: "canvas", qty: 100, attributes: {labels: { valueList : …
```
> fix:addresses not_in filter query for array type field - attributes.lables

- entity-service-impl/src/main/java/org/hypertrace/entity/data/service/EntityNormalizer.java
- entity-service-impl/src/test/java/org/hypertrace/entity/data/service/EntityNormalizerTest.java
This change relaxes the requirements on upsert so the identifying attributes of a V1-typed entity need not be an exact match of the defined identifying attributes for that type. As long as they're a supserset, the upsert is allowed. In other words, the defined identifying attributes are considered a minimum set.
This supports changes to add new identifying attributes to existing types without A. breaking existing IDs if new identifying attribute is not present and B. without breaking compatibility for existing upsert paths (which would otherwise require concurrent changes in the entity type config and the upsert path).
Updated and ran unit tests. Ran integration tests
> refactor: allow extra identifying attributes on entity upsert

- entity-service-impl/build.gradle.kts
- entity-service/build.gradle.kts
Updates doc-store version to include postgres impl of exists, not-exists, and NEQ filters 
- https://github.com/hypertrace/document-store/pull/35
- https://github.com/hypertrace/document-store/pull/33
> chore: bump doc-store version to include postgres impl of exits, not-exsits and neq

- entity-service-api/src/main/proto/org/hypertrace/entity/data/service/v1/entity_data_request.proto
- entity-service-api/src/main/proto/org/hypertrace/entity/data/service/v1/entity_data_service.proto
- entity-service-impl/src/main/java/org/hypertrace/entity/data/service/EntityDataServiceImpl.java
- entity-service-impl/src/main/java/org/hypertrace/entity/data/service/EntityNormalizer.java
- entity-service-impl/src/main/java/org/hypertrace/entity/data/service/EntityV2TypeDocKey.java
- entity-service-impl/src/test/java/org/hypertrace/entity/data/service/EntityNormalizerTest.java
- entity-service-impl/src/test/java/org/hypertrace/entity/data/service/EntityV2TypeDocKeyTest.java
Unlike V1 entities, V2 entities have IDs that are not controlled by entity service (to allow calculating without talking to ES), which means we can't guarantee their global uniqueness - that's up to the id implementation. This change updates the APIs to allow providing entity types in the byId-typed APIs, falling back to the existing behavior if they're not provided. If they _are_ provided *and* are a v2 entity type, a new key format is used that includes the entity type to keep the data from stomping on potential entities of a different type. Because no v2 entities are stored in EDS today, this change should be fully backwards compatible.
Ran with this as part of a larger e2e change, added UTs here.
> fix: support working with v2 typed entities

- entity-service-impl/build.gradle.kts
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/EntityAttributeMapping.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/EntityQueryConverter.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/EntityQueryServiceImpl.java
- entity-service-impl/src/test/java/org/hypertrace/entity/query/service/EntityAttributeMappingTest.java
- entity-service-impl/src/test/java/org/hypertrace/entity/query/service/EntityQueryConverterTest.java
- entity-service-impl/src/test/java/org/hypertrace/entity/query/service/EntityQueryServiceImplTest.java
- entity-service/src/main/java/org/hypertrace/entity/service/EntityService.java
- entity-service/src/main/resources/configs/common/application.conf
- helm/templates/entity-service-config.yaml
- helm/values.yaml
This change is the flipside of https://github.com/hypertrace/entity-service/pull/92 - it adds support for retrieving v2 typed entities via EQS. Previously, we had two different schemas for an entity - one defined in attribute service, and a corresponding one mapping it into entity service. With v2 schemas, entities are only defined via attributes - the entity definition simply specifies important attributes such as the name and identifier. Full backwards compatibility
Tested E2E, added + updated UTs
> fix: support retrieving entity attributes for v2 typed ents

- entity-service-api/src/main/proto/org/hypertrace/entity/data/service/v1/entity_data_request.proto
- entity-service-api/src/main/proto/org/hypertrace/entity/data/service/v1/entity_data_service.proto
- entity-service-api/src/main/proto/org/hypertrace/entity/type/service/v2/entity_type_service.proto
- entity-service-impl/src/main/java/org/hypertrace/entity/data/service/EntityDataServiceImpl.java
- entity-service-impl/src/main/java/org/hypertrace/entity/data/service/UpsertConditionMatcher.java
- entity-service-impl/src/test/java/org/hypertrace/entity/data/service/UpsertConditionMatcherTest.java
- entity-service/build.gradle.kts
- entity-service/src/integrationTest/java/org/hypertrace/entity/service/service/EntityDataServiceTest.java
This change adds a new upsert API that has two main distinctions from the existing API:
1. Instead of overwriting an existing entity, it will merge with it
2. It supports a predicate that will be evaluated against any existing entity, to check before proceeding.
Both changes help support easier high write volume use cases - for example, multiple enrichers running in parallel. The merge case saves us from having to do two sequential round trips (to prevent overwriting data) in the update case, and the predicate helps us to better enforce write consistency - that is, ensuring a newer update doesn't arrive earlier than an older. Note this is not a full consistency guarantee, but likely good enough for our purposes.
Ran E2E, also added ITs and UTs.
> feat: add merge upsert api with condition support

- entity-data-service-rx-client/src/main/java/org/hypertrace/entity/data/service/rxclient/EntityDataCachingClient.java
- entity-data-service-rx-client/src/main/java/org/hypertrace/entity/data/service/rxclient/EntityDataClient.java
- entity-data-service-rx-client/src/main/java/org/hypertrace/entity/data/service/rxclient/EntityKey.java
- entity-data-service-rx-client/src/test/java/org/hypertrace/entity/data/service/rxclient/EntityDataCachingClientTest.java
- entity-data-service-rx-client/src/test/java/org/hypertrace/entity/data/service/rxclient/EntityKeyTest.java
This new client api allows throttling writes. This allows ingestion to write at high volume, while only periodically pushing those changes to the server.
Tested E2E, added UT
> feat: add async entity write to rx client

- entity-service-impl/src/main/java/org/hypertrace/entity/type/service/v2/model/EntityTypeDocument.java
- entity-service-impl/src/test/java/org/hypertrace/entity/type/service/v2/model/EntityTypeDocumentTest.java
Write timestamp attribute key to database. Without this change it was being silently ignored. This was missed because the key is not needed for querying - it's currently only used for optimistic locking, which is just skipped if it's not set - so no visible difference.
Verified after adding that this key was being written.
> fix: write timestamp attribute key

- entity-service-impl/src/main/java/org/hypertrace/entity/type/service/v2/model/EntityTypeDocument.java
- entity-service-impl/src/test/java/org/hypertrace/entity/type/service/v2/model/EntityTypeDocumentTest.java
Make name and timestamp keys optional - both to support backwards compatibility but also for entity definitions that don't use those fields.
Ran into issues with previous rev in e2e env due to existing upgrades that missed the new key. Now making it optional.
> fix: backwards compat for existing entity type docs

- entity-service-api/src/main/proto/org/hypertrace/entity/type/service/v2/entity_type_service.proto
- entity-service-impl/src/main/java/org/hypertrace/entity/type/service/v2/model/EntityTypeDocument.java
- entity-service-impl/src/test/java/org/hypertrace/entity/type/service/v2/model/EntityTypeDocumentTest.java
This adds support for requiring keys on v2 entity types that are ingested based on config during enrichment. Previously, any time a valid ID can be generated, an entity would be formed (so, for example, if an id is based on a hash of several attributes and only one is present, it would still form an entity). Now, we can require any number of attributes to be present to give more control over entity definition. A better version of this would be full blown predicate support, but given that entity type service doesn't have those constructs today, it felt like overkill to build that out just yet... instead, I wrapped the concept such that other types of conditions could be added in the future.
Updated UTs, validated behavior e2e
> feat: add support for required keys on entity attributes

- entity-service-client/build.gradle.kts
- entity-service-client/src/main/java/org/hypertrace/entity/data/service/client/EdsCacheClient.java
Currently we have no metrics for the various cache used in EdsCacheClient. 
Adding metrics for them.
The metrics are directly exported to Prometheus. Hence, there are no tests performed for this. Since the tests for the meter registry are already is place in the service-framework.
> EdsCache Client Metrics

- entity-data-service-rx-client/src/main/java/org/hypertrace/entity/data/service/rxclient/EntityDataCachingClient.java
previously, a pending update could be retrieved and modified after it
has started updating, causing it to npe and leak memory
> fix: threading issue in entity caching client

- entity-data-service-rx-client/src/main/java/org/hypertrace/entity/data/service/rxclient/EntityDataCachingClient.java
Switching from a RW lock to mutual exclusion since adding updates is also not thread safe.
> fix: address more concurrency concerns in caching client

- entity-service-impl/build.gradle.kts
Use newer attribute client with better performing client (builds errors lazily, less exception filling)
> chore: use newer attribute client with lazy errors

- entity-service-impl/build.gradle.kts
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/EntityQueryServiceImpl.java
- entity-service-impl/src/test/java/org/hypertrace/entity/query/service/EntityQueryServiceImplTest.java
- entity-service/build.gradle.kts
Reverts hypertrace/entity-service#119
> Revert "BulkEntityUpdate API"

- .snyk
- entity-data-service-rx-client/build.gradle.kts
- entity-data-service-rx-client/src/main/java/org/hypertrace/entity/data/service/rxclient/EntityDataCachingClient.java
- entity-data-service-rx-client/src/main/java/org/hypertrace/entity/data/service/rxclient/EntityDataClient.java
- entity-data-service-rx-client/src/main/java/org/hypertrace/entity/data/service/rxclient/EntityKey.java
- entity-data-service-rx-client/src/test/java/org/hypertrace/entity/data/service/rxclient/EntityDataCachingClientTest.java
The motivation here is that the previous client API had major performance issues. Given the purpose of this api, high traffic writes, reducing to a simpler API makes sense for the safe of perf.
There were two major issues previously:
1. Each call returned a single, which requires a new subscription for each invocation. The subscriptions aren't _too_ heavy, but that's still a lot of unnecessary churn considering we don't actually read the result anywhere today.
2. By creating a subscription, the entire observable pipeline, including its lambda captures are retained in memory until the subscription is resolved (by default, 15s). This means that we're always holding 15s of ingestion data for no good reason. This needs to be fixed on the caller side, since the client can't control the context …
> fix: change entity client to not return single

- entity-service-api/src/main/proto/org/hypertrace/entity/query/service/v1/entity_query_request.proto
- entity-service-api/src/main/proto/org/hypertrace/entity/query/service/v1/entity_query_service.proto
- entity-service-impl/build.gradle.kts
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/EntityQueryServiceImpl.java
- entity-service/build.gradle.kts
- entity-service/src/integrationTest/java/org/hypertrace/entity/service/service/EntityQueryServiceTest.java
1. Exposing it in EntityQueryService as other required helper classes and method exists in that class. Don't like it. However exposing it in EntityDataService will require some major code refactoring.
2. Hard-coded suffix for array value to ".valueList.values".  Suggestions are welcome.
> Changes to perform bulk operation on attribute with array value

- .snyk
- entity-data-service-rx-client/build.gradle.kts
- entity-service-api/build.gradle.kts
- entity-service-change-event-api/build.gradle.kts
- entity-service-change-event-generator/build.gradle.kts
- entity-service-client/build.gradle.kts
- entity-service-impl/build.gradle.kts
- entity-service/build.gradle.kts
- entity-service/src/main/resources/configs/common/application.conf
- entity-type-service-rx-client/build.gradle.kts
This is the second half of fix for https://github.com/hypertrace/hypertrace-ui/issues/1061 . In that ticket, previously @skjindal93 started populating serviceName on API entities but instead of using the new attributeId which would be mapped automatically, it used the old entity service key which requires an explicit subpath mapping. This PR adds that mapping.
Built and ran locally, verified behavior.
Closes https://github.com/hypertrace/hypertrace-ui/issues/1061
> fix: map api service name

- entity-service-api/build.gradle.kts
- entity-service-client/build.gradle.kts
- entity-service-impl/build.gradle.kts
- entity-service/build.gradle.kts
- entity-service/src/integrationTest/java/org/hypertrace/entity/service/client/config/EntityServiceTestConfig.java
- entity-service/src/integrationTest/java/org/hypertrace/entity/service/service/EntityDataServiceRelationshipsTest.java
- entity-service/src/integrationTest/java/org/hypertrace/entity/service/service/EntityDataServiceTest.java
- entity-service/src/integrationTest/java/org/hypertrace/entity/service/service/EntityQueryServiceTest.java
- entity-service/src/integrationTest/java/org/hypertrace/entity/service/service/EntityTypeServiceTest.java
- entity-service/src/integrationTest/resources/configs/attribute-service/application.conf
- entity-service/src/integrationTest/resources/configs/entity-service/application.conf
Additional integration test for filtering on composite values (arrays and maps)
> Add integration test for filtering on composite values (arrays and maps)

- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/filter/FilterConverterFactory.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/filter/FilterConverterFactoryImpl.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/filter/FilterModule.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/filter/LogicalExpressionConverter.java
- entity-service-impl/src/test/java/org/hypertrace/entity/query/service/converter/filter/FilterConverterFactoryImplTest.java
- entity-service-impl/src/test/java/org/hypertrace/entity/query/service/converter/filter/FilterConverterTest.java
- entity-service-impl/src/test/java/org/hypertrace/entity/query/service/converter/filter/LogicalExpressionConverterTest.java
* Fixed the single-child filter case for Logical Expression conversion
* Handled the empty child filter case for Logical Expression conversion
Added unit tests
> Fix for single-child filter case of logical expression conversion

- entity-service-impl/build.gradle.kts
- entity-service/build.gradle.kts
Updated the document-store version
> Updated the document-store version

- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/response/getter/ListValueGetter.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/response/getter/MapValueGetter.java
- entity-service-impl/src/test/java/org/hypertrace/entity/query/service/converter/response/DocumentConverterTest.java
- entity-service-impl/src/test/resources/response/nested_document.json
Fix empty lists and empty maps
Added unit tests
> Fix empty lists and empty maps

- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/filter/ArrayFilteringExpressionConverter.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/filter/FilteringExpressionConverterBase.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/identifier/ArrayElementSuffixAddingIdentifierConverter.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/identifier/ArraySuffixAddingIdentifierConverter.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/identifier/IdentifierConverterFactoryImpl.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/identifier/MapSuffixAddingIdentifierConverter.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/identifier/PrimitiveSuffixAddingIdentifierConverter.java
- entity-service/src/integrationTest/java/org/hypertrace/entity/service/service/EntityQueryServiceTest.java
Fix for equality comparison of single values with arrays
Added integration tests
> Fix for equality comparison of single values with arrays

- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/identifier/IdentifierConverterFactoryImpl.java
Fix missing identifier converter
Tested end-to-end using GraphQL client
> Fix missing identifier converter

- entity-service-impl/build.gradle.kts
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/EntityQueryConverter.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/EntityQueryServiceImpl.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/OrderByConverter.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/aggregation/GroupByConverter.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/filter/ArrayFilteringExpressionConverter.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/filter/ExtraFiltersApplier.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/filter/ExtraFiltersApplierImpl.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/filter/FilterConverter.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/filter/FilterConverterFactory.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/filter/FilterConverterFactoryImpl.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/filter/FilteringExpressionConverter.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/filter/LogicalExpressionConverter.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/filter/MapFilteringExpressionConverter.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/filter/PrimitiveFilteringExpressionConverter.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/filter/RelationalExpressionConverter.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/selection/SelectionConverter.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/selection/SelectionFactory.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/selection/SelectionFactoryImpl.java
- entity-service-impl/src/test/java/org/hypertrace/entity/query/service/EntityQueryServiceImplTest.java
- entity-service-impl/src/test/java/org/hypertrace/entity/query/service/converter/OrderByConverterTest.java
- entity-service-impl/src/test/java/org/hypertrace/entity/query/service/converter/filter/ExtraFiltersApplierTest.java
- entity-service-impl/src/test/java/org/hypertrace/entity/query/service/converter/filter/FilterConverterTest.java
- entity-service-impl/src/test/java/org/hypertrace/entity/query/service/converter/filter/LogicalExpressionConverterTest.java
- entity-service-impl/src/test/java/org/hypertrace/entity/query/service/converter/filter/RelationalExpressionConverterTest.java
- entity-service/build.gradle.kts
- entity-service/src/integrationTest/java/org/hypertrace/entity/service/service/EntityQueryServiceTest.java
- entity-service/src/main/resources/configs/common/application.conf
- helm/templates/entity-service-config.yaml
- helm/values.yaml
* Surround the new query DTO querying under a disabled flag with the old query DTO querying as default
* Updated the document store version with renamed classes
Executed end-to-end tests
> Wrap new query DTO querying under a flag

- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/EntityQueryServiceImpl.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/aggregation/AggregateExpressionConverter.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/aggregation/AggregationAliasProvider.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/aggregation/AggregationModule.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/selection/SelectionFactoryImpl.java
- entity-service-impl/src/test/java/org/hypertrace/entity/query/service/converter/aggregation/AggregationAliasProviderTest.java
- entity-service-impl/src/test/java/org/hypertrace/entity/query/service/converter/aggregation/AggregationExpressionConverterTest.java
- entity-service-impl/src/test/java/org/hypertrace/entity/query/service/converter/selection/SelectionFactoryImplTest.java
- entity-service/src/integrationTest/java/org/hypertrace/entity/service/service/EntityQueryServiceTest.java
Replace aggregate expressions with functions.
Note that only aggregate functions are supported in this implementation.
* Unit and integration tests
> Replace aggregate expressions with functions.

- .snyk
- entity-service-api/src/main/proto/org/hypertrace/entity/query/service/v1/entity_query_request.proto
- entity-service-api/src/main/proto/org/hypertrace/entity/query/service/v1/request.proto
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/EntityQueryServiceImpl.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/QueryConverter.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/accessor/ExpressionOneOfAccessor.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/aggregation/AggregationModule.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/aggregation/GroupByConverter.java
- entity-service-impl/src/test/java/org/hypertrace/entity/query/service/converter/accessor/ExpressionOneOfAccessorTest.java
- entity-service-impl/src/test/java/org/hypertrace/entity/query/service/converter/aggregation/GroupByConverterTest.java
- entity-service/src/integrationTest/java/org/hypertrace/entity/service/service/EntityQueryServiceTest.java
* Removed the reduandant AggregateExpression proto
* Unwrapped GroupByExpression to directly use Expression
* Unit and integration tests
> Remove redundant protos

- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/EntityQueryConverter.java
Some integers fields still exists in entities, for doing the bulkUpdate of those attributes, we need the conversion of int.
> Adding int value conversion for attribute value

- entity-service-impl/build.gradle.kts
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/ConverterModule.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/FromClauseConverter.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/QueryConverter.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/aggregation/AggregationAliasProvider.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/aggregation/AggregationColumnProvider.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/identifier/ArrayElementSuffixAddingIdentifierConverter.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/identifier/ArrayPathSuffixAddingIdentifierConverter.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/identifier/ArraySuffixAddingIdentifierConverter.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/identifier/IdentifierExpressionConverter.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/identifier/MapSuffixAddingIdentifierConverter.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/identifier/PrimitiveSuffixAddingIdentifierConverter.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/identifier/SuffixAddingIdentifierConverter.java
- entity-service-impl/src/test/java/org/hypertrace/entity/query/service/converter/FromClauseConverterTest.java
- entity-service-impl/src/test/java/org/hypertrace/entity/query/service/converter/aggregation/AggregationAliasProviderTest.java
- entity-service-impl/src/test/java/org/hypertrace/entity/query/service/converter/aggregation/AggregationColumnProviderTest.java
- entity-service-impl/src/test/java/org/hypertrace/entity/query/service/converter/identifier/IdentifierExpressionConverterTest.java
- entity-service/build.gradle.kts
Aggregations and grouping can now be applied on multi-value attributes
> Multi value attribute grouping support

- entity-service-api/src/main/proto/org/hypertrace/entity/constants/v1/entity_attribute.proto
Added a new attribute in API-section which maintains the information that what was the source of api-discovery - Platform or Agent.
Ran unit tests locally
> Add api-naming source attribute

- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/filter/LogicalExpressionConverter.java
- entity-service-impl/src/test/java/org/hypertrace/entity/query/service/converter/filter/LogicalExpressionConverterTest.java
Default child filter case is handled
Added unit tests
> Fix default child filter case in LogicalExpressionConverter

- entity-service-impl/build.gradle.kts
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/aggregation/AggregateExpressionConverter.java
- entity-service-impl/src/test/java/org/hypertrace/entity/query/service/converter/aggregation/AggregationAliasProviderTest.java
- entity-service-impl/src/test/java/org/hypertrace/entity/query/service/converter/aggregation/AggregationColumnProviderTest.java
This PR updates document store library version(accordingly impl changes) and adds conversion for DISTINCT_ARRAY operator. It is the same as the current DISTINCT. Current DISTINCT support would be removed once the upstream services are migrated.
Updated unit tests and verified that they run successfully.
> chore: add DISTINCT_ARRAY operator

- entity-service-factory/build.gradle.kts
- entity-service-impl/build.gradle.kts
- entity-service/build.gradle.kts
This PR updates document store to its backward compatible version(comes with release attached to https://github.com/hypertrace/document-store/pull/129)
> chore: update document store

- entity-service-api/src/main/proto/org/hypertrace/entity/query/service/v1/entity_query_service.proto
- entity-service-factory/build.gradle.kts
- entity-service-impl/build.gradle.kts
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/EntityQueryConverter.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/EntityQueryServiceImpl.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/UpdateConverter.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/ValueHelper.java
- entity-service-impl/src/test/java/org/hypertrace/entity/query/service/EntityQueryServiceImplTest.java
- entity-service-impl/src/test/java/org/hypertrace/entity/query/service/converter/UpdateConverterTest.java
- entity-service/build.gradle.kts
- entity-service/src/integrationTest/java/org/hypertrace/entity/service/service/EntityQueryServiceTest.java
Added support for the update operators in addition to SET.
Added necessary unit and integration tests
> Update operators implementation

- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/ValueHelper.java
- entity-service-impl/src/test/java/org/hypertrace/entity/query/service/converter/ValueHelperTest.java
- entity-service/src/integrationTest/java/org/hypertrace/entity/service/service/EntityQueryServiceTest.java
- entity-service/src/integrationTest/resources/configs/entity-service/application.conf
Previously, the bulk update API was getting invoked only with non-default values (E.g.: 0 for int, false for boolean, etc). Since default values are not included in the proto. to JSON converter, it was a problem. Now, since the bulk update is getting invoked even for the default values, an empty object is getting written in the database, which is causing issues while reading. This PR aims at manually generating the JSON document (instead of relying on the proto. converter).
Added unit and integration tests
> Fix issues with bulk update by manually generating the JSON document

- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/filter/PrimitiveFilteringExpressionConverter.java
Timestamps are their own type, but all writers store them as longs. When filtering, we need to map timestamp attributes back to that storage format.
> fix: timestamp filters should be mapped to longs

- helm/Chart.yaml
Updating sub-chart version to latest: https://github.com/hypertrace/config-bootstrapper/releases/tag/0.2.42
> chore: updating sub-chart version to latest

- entity-service-change-event-generator/build.gradle.kts
- entity-service-factory/build.gradle.kts
- entity-service-impl/build.gradle.kts
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/EntityQueryServiceImpl.java
- entity-service-impl/src/test/java/org/hypertrace/entity/query/service/EntityQueryServiceImplTest.java
- entity-service/build.gradle.kts
- entity-service/src/integrationTest/resources/configs/entity-service/application.conf
- helm/templates/entity-service-config.yaml
- helm/values.yaml
- owasp-suppressions.xml
Also, making it configurable through helm values.
> update max string length for bulk update matching all filter api

- entity-service-impl/src/main/java/org/hypertrace/entity/service/util/DocStoreConverter.java
- entity-service-impl/src/test/java/org/hypertrace/entity/service/util/DocStoreConverterTest.java
> fix: handle NOT_IN operator transformation
