hypertrace/entity-service

- .circleci/config.yml
- .snyk
- entity-service-client/build.gradle.kts
- entity-service-impl/build.gradle.kts
- entity-service/build.gradle.kts
> Update grpc utils with changes for binary headers

- entity-service-client/src/main/java/org/hypertrace/entity/data/service/client/EdsCacheClient.java
This is not an erroneous scenario, so converting logging messages as a warning.
> Update logging level to warn for eds cache client

- entity-service/src/main/resources/configs/common/application.conf
- adding prefix so we can differentiate JVM metrics for the specific service
> Adding metrics reporter for the service

- helm/Chart.yaml
> Update CB helm chart version

- helm/Chart.yaml
update config bootstrapper to 0.1.12
> update config bootstrapper to 0.1.12

- README.md
- entity-service-client/build.gradle.kts
- entity-service-impl/build.gradle.kts
- entity-service/build.gradle.kts
This PR,
- Adds query architecture diagram and explains entity service in it's context
- Adds build steps and image source in README
> Adds query architecture, working, build steps and image source in README

- entity-service-client/src/main/java/org/hypertrace/entity/data/service/client/DefaultEdsClientProvider.java
- entity-service-client/src/main/java/org/hypertrace/entity/data/service/client/EdsCacheClient.java
- entity-service-client/src/main/java/org/hypertrace/entity/data/service/client/EntityDataServiceClient.java
- entity-service-client/src/main/java/org/hypertrace/entity/data/service/client/EntityDataServiceClientProvider.java
- entity-service-client/src/main/java/org/hypertrace/entity/query/service/client/EntityQueryServiceClient.java
- entity-service-client/src/main/java/org/hypertrace/entity/type/service/client/EntityTypeServiceClient.java
This will require for fixing the issue - https://github.com/hypertrace/hypertrace/issues/89
See reference - https://github.com/hypertrace/attribute-service/pull/24
> cleaning client interface to support channel management by caller

- .snyk
Remove GRPC (which has been patched) and add ionetty (which won't be fixed until 5.x release - https://github.com/netty/netty/issues/10806#issuecomment-729156835 ) exclusion
Verified snyk results locally
- [n/a] I have added tests that prove my fix is effective or that my feature works
> chore: update snyk ignores

- .circleci/config.yml
- entity-service-impl/build.gradle.kts
- entity-service/build.gradle.kts
Update framework version for vulnerability fixes, limit snyk to run on runtime code.
- [n/a] I have added tests that prove my fix is effective or that my feature works
> chore: update vulnerable dependencies

- entity-service-impl/build.gradle.kts
- entity-service/build.gradle.kts
Document Store v0.4.5 adds lastUpdatedTime field as a long which is useful for document filtering based last updated timestamp
> Updates Document Store version

- entity-service-impl/build.gradle.kts
- entity-service/build.gradle.kts
Updates the latest version of the service framework in the context of addressing the issue - https://github.com/hypertrace/hypertrace/issues/137. Pl refer discussion on the issue and associated merged PR for further information.
> chore: updates service framework version to address security concern

- entity-service-api/src/main/proto/org/hypertrace/entity/constants/v1/entity_attribute.proto
Removes redundant API attributes
No testing required. Verified whether the enums are not used anywhere by doing a Github code search
> chore(api): removes redundant attributes

- entity-service-impl/build.gradle.kts
- entity-service-impl/src/main/java/org/hypertrace/entity/data/service/EntityDataServiceImpl.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/EntityQueryConverter.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/EntityQueryServiceImpl.java
- entity-service-impl/src/main/java/org/hypertrace/entity/service/util/DocStoreConverter.java
- entity-service-impl/src/test/java/org/hypertrace/entity/query/service/EntityQueryConverterTest.java
- entity-service-impl/src/test/java/org/hypertrace/entity/service/util/DocStoreConverterTest.java
- entity-service/build.gradle.kts
- entity-service/src/integrationTest/java/org/hypertrace/entity/service/service/EntityQueryServiceTest.java
- entity-service/src/integrationTest/resources/configs/entity-service/application.conf
Flowing down the selections requested on EntityQueryRequest to doc store projections. Depends on https://github.com/hypertrace/document-store/pull/28
Added unit tests. Verified end to end by port forwarding various services and loading all the screens on the UI
> feat: entity query selections to projections in doc store

- entity-service-api/src/main/proto/org/hypertrace/entity/constants/v1/entity_attribute.proto
Added host header attribute to be added in Entities as attributes
> chore: added host header attribute

- entity-service-api/src/main/proto/org/hypertrace/entity/query/service/v1/entity_query_request.proto
- entity-service-api/src/main/proto/org/hypertrace/entity/query/service/v1/entity_query_service.proto
- entity-service-api/src/main/proto/org/hypertrace/entity/query/service/v1/request.proto
- entity-service-api/src/main/proto/org/hypertrace/entity/query/service/v1/response.proto
- entity-service-client/src/main/java/org/hypertrace/entity/query/service/client/EntityQueryServiceClient.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/EntityQueryServiceImpl.java
- entity-service-impl/src/test/java/org/hypertrace/entity/query/service/EntityQueryServiceImplTest.java
- entity-service/src/integrationTest/java/org/hypertrace/entity/service/service/EntityQueryServiceTest.java
Added support to fetch total number of entities
Added unit tests
> feat(entity-query-service): total entities api

- helm/Chart.yaml
updated config-bootstrapper dependency version to latest i.e. 0.2.4
> chore: bump up the version of config bootstrapper

- helm/Chart.yaml
- Updating Config-bootstrapper version to add changes from https://github.com/hypertrace/config-bootstrapper/pull/44
NA
>  chore: updated config-bootstrapper version

- helm/Chart.yaml
- Updating Config-bootstrapper version to add changes from https://github.com/hypertrace/config-bootstrapper/pull/47
NA
> chore: updates config boostrapper chart

- .snyk
- entity-data-service-rx-client/build.gradle.kts
- entity-service-api/build.gradle.kts
- entity-service-client/build.gradle.kts
- entity-service-client/src/test/java/org/hypertrace/entity/data/service/client/EntityDataServiceClientRetriesTest.java
- entity-service-impl/build.gradle.kts
- entity-service/build.gradle.kts
- entity-service/src/integrationTest/java/org/hypertrace/entity/service/service/EntityDataServiceTest.java
- entity-type-service-rx-client/build.gradle.kts
Update dependencies
Ran + updated UTs
> chore: update dependencies

- entity-service-impl/build.gradle.kts
- entity-service/build.gradle.kts
Update framework to fix vulns.
- [N/A] I have added tests that prove my fix is effective or that my feature works
> chore: update vulnerabilities

- .github/CODEOWNERS
- helm/Chart.yaml
Update to newer config bootstrapper which includes newer entity clients to support bootstrapping latest features.
> chore: update config bootstrapper

- helm/Chart.yaml
updates config bootstrapper version to incorporate changes done to add API trace error count attribute.
> chore: update config bootstrapper version for API trace error count 

- helm/Chart.yaml
The new version of cb has the last entity client which supports entity formation conditions
> chore: update config bootstrapper for entity formation

- helm/Chart.yaml
- updates config bootstrapper version to latest
> chore: updates config bootstrapper version

- .snyk
- entity-service-impl/build.gradle.kts
- entity-service/build.gradle.kts
- update document-store version to incorporate a fix - https://github.com/hypertrace/document-store/pull/52
> chore: update document store version for hasNext fix

- entity-service-impl/build.gradle.kts
- entity-service/build.gradle.kts
Update platform framework to bring in newer jetty (snyk raised issues on previous version)
> chore: update framework version for latest deps

- entity-service-client/src/main/java/org/hypertrace/entity/data/service/client/EdsCacheClient.java
- entity-service-client/src/main/java/org/hypertrace/entity/service/client/config/EntityServiceClientCacheConfig.java
Enhanced the EdsCacheClient with support for configuring refreshAfterWrite and also async cache reloading.
> Enhanced EdsCacheClient to support async reloading and refreshAfterWrite

- helm/Chart.yaml
Updated the config bootstrapper version.
> Updated config bootstrapper version

- entity-data-service-rx-client/build.gradle.kts
- entity-service-change-event-generator/build.gradle.kts
- entity-service-client/build.gradle.kts
- entity-service-impl/build.gradle.kts
- entity-service/build.gradle.kts
- entity-type-service-rx-client/build.gradle.kts
> fix: update vulnerable dep

- entity-service-impl/build.gradle.kts
- entity-service-impl/src/test/java/org/hypertrace/entity/TestUtils.java
- entity-service-impl/src/test/java/org/hypertrace/entity/data/service/IdentifyingAttributeCacheTest.java
- entity-service-impl/src/test/java/org/hypertrace/entity/query/service/EntityQueryServiceImplTest.java
- entity-service/build.gradle.kts
Upgrading doc-store version which supports partial updates having empty object values
> Upgrade doc store version

- entity-service/src/main/java/org/hypertrace/entity/service/EntityService.java
Updated data store health reporting to return health before launching (since doStart does not return until the service has exited). Also cleaned up future upon server stop.
> fix: update data store to report health before launching

- entity-service-client/build.gradle.kts
- entity-service-factory/build.gradle.kts
- entity-service-impl/build.gradle.kts
- entity-service/build.gradle.kts
- entity-service/src/main/java/org/hypertrace/entity/service/EntityService.java
Update service framework version
> chore: update service framework version

- .github/workflows/pr-build.yml
- build.gradle.kts
added container scanning to entity-service repo
> added container scanning to entity-service repo

- entity-service-factory/build.gradle.kts
- entity-service-impl/build.gradle.kts
- entity-service/build.gradle.kts
- update doc-store version to latest
> chore: update doc-store version to latest

- entity-service-factory/build.gradle.kts
- entity-service-impl/build.gradle.kts
- entity-service/build.gradle.kts
Include the fix for the selection clause in document-store - https://github.com/hypertrace/document-store/pull/115
> chore : update doc-store lib version

- entity-service-factory/build.gradle.kts
- entity-service-impl/build.gradle.kts
- entity-service/build.gradle.kts
- upgrade doc-store libs to latest version
> chore: upgrade doc-store lib for latest fixes

- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/EntityQueryConverter.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/EntityQueryServiceImpl.java
- entity-service-impl/src/test/java/org/hypertrace/entity/query/service/EntityQueryServiceImplTest.java
- entity-service/src/integrationTest/java/org/hypertrace/entity/service/service/EntityQueryServiceTest.java
- entity-service/src/main/resources/configs/common/application.conf
- helm/templates/entity-service-config.yaml
- helm/values.yaml
Removed the queryAggregationEnabled flag as the aggregate() is supported for both mongo and postgres now.
> Reverted #167 to remove the queryAggregationEnabled flag

- .github/workflows/pr-test.yml
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/converter/filter/PrimitiveFilteringExpressionConverter.java
- entity-service/src/integrationTest/java/org/hypertrace/entity/service/service/EntityQueryServiceTest.java
Get the ValueType from db instead of rhs value
> fix: Get the ValueType from db instead of RHS

- .github/workflows/publish.yml
> Empty PR to fix latest tag

- entity-service-api/src/main/proto/org/hypertrace/entity/constants/v1/entity_attribute.proto
> Add agent entity id in constants for enriching spans with agent entity id

- entity-service-api/src/main/proto/org/hypertrace/entity/constants/v1/entity_attribute.proto
Reverts hypertrace/entity-service#262
> Revert "Add agent entity id in constants for enriching spans with agent entity id"

- entity-service-attribute-translator/build.gradle.kts
- entity-service-attribute-translator/src/main/java/org/hypertrace/entity/attribute/translator/EntityAttributeChangeEvaluator.java
- entity-service-impl/src/main/java/org/hypertrace/entity/query/service/EntityQueryServiceImpl.java
> Add logs to debug change-event not generated from bulkUpdateAllMatchingFilters api

- entity-service/src/integrationTest/resources/configs/entity-service/application.conf
Reverts hypertrace/entity-service#287
> Revert "Introduce ids for domain entity type"
